### ISSUE TITLE
I-DE logs in correctly, but data does not show up in energy dashboard (had corruputed database) 

### ISSUE THREAD

**Issue by hartmood** [ldotlopez/ha-ideenergy#55]
Since the 4th of October, my energy dashboard and the I-DE consumption have not worked anymore. Probably, this has been caused by an update on the beta channel that corrupted my SQLite database. Multiple re-installations of SQLite, MariaDB, and I-DE did not bring back data to the energy dashboard. The energy dashboard is empty, and both relevant sensors show the data from the 4th. I can see that the I-DE energy plugin logs in correctly, but data needs to be written to the correct tables. 

**Describe the bug**
Data should show up as it did before the corrupt database. 

**To Reproduce**
I have deleted and reinstalled databases (Sqlite, MariaDB) or I-DE and have yet to return the energy board data successfully. 

**Environment**
Raspi 4 - no docker
Home Assistant 2023.10.2
Supervisor 2023.10.0
Operating System 10.5
Frontend 20231005.0 - latest

**Expected behavior**
Data written into the energy dashboard

**Logs**
2023-10-13 09:54:19.720 INFO (MainThread) [ideenergy] <ideenergy.Client username=b@xxx.xxx, contract=215315583>: '215315583' contract selected
2023-10-13 09:54:19.720 INFO (MainThread) [ideenergy] <ideenergy.Client username=b@xxx.xxx, contract=215315583>: successful authentication
2023-10-13 09:58:50.476 INFO (MainThread) [ideenergy] <ideenergy.Client username=b@xxx.xxx, contract=215315583>: '215315583' contract selected
2023-10-13 09:58:50.477 INFO (MainThread) [ideenergy] <ideenergy.Client username=b@xxx.xxx, contract=215315583>: successful authentication

**Comment by Zsoltt-dom** [comment]
Same here, no data is being shown. And it complains about a database error.

**Comment by hartmood** [comment]
In my case, the SQLite database was corrupted. All data is gone, unfortunately. Although I could set up a new database, I-DE still doesn’t work. Maybe I-DE was the cause of the troubles?

**Comment by ldotlopez** [comment]
Hi,

I didn't have enough information to check where the problem is.

I'm running myself the latest version both from Home Assistant and this integration without issues.

If you still can reproduce the bug enable debug with the '-v' switch from hass or adding this lines in the configuration and post the logs.

```
logger:
  default: warning
  logs:
    ideenergy: warning
    custom_components.ideenergy.datacoordinator: debug
    custom_components.ideenergy.sensor: debug
    custom_components.ideenergy.updates: debug
    custom_components.ideenergy.fixes: debug
    custom_components.ideenergy: debug
    homeassistant_historical_sensor: debug
```
